### ISSUE TITLE
Version 0.7.0 pre-release checklist (JSON API)

### ISSUE THREAD

**Issue by aidanlister** [freakboy3742/pyxero#76]
I've just pushed up a change which eliminates the XML parsing for all data retrieval (GET, and the returned response from PUT/PATCH). This wipes out all the walk_dom crap which was causing all sorts of inconsistent responses (dicts instead of lists for singular items) and eliminates a tonne of complexity.

I've also cleaned up the xmlwriting part by explicitly translating between plural and singular verbs -- this will cause problems as I'm sure we haven't included all the mappings we need -- but it's better to have an explicit list rather than try and map between plurals when Xero isn't always consistent.

So, let's get some eyeballs on HEAD and see if it's stable enough to push out as a 0.7.0-alpha release in the next month.

- [x] Have some people use HEAD and confirm everything's working
- [x] Merge all PRs and close all remaining issues
- [x] More unit tests
- [x] Add examples for Public and Partner
- [x] Roll alpha release
- [x] Roll stable release
